# PyTorch Tensor Notebook

### The Data Spartan

#### Helpful Resourses: 
1. https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
2. https://pytorch.org/docs/stable/tensors.html

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate 
computing.

In [1]:
from __future__ import print_function
import torch

# Tensor Initialization

#### An Uninitialized 5 X 4 Tensor 

In [2]:
x = torch.empty(5, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


#### A Randomly Initialized 5 x 4 Tensor

In [3]:
x = torch.rand(5, 4)
print(x)

tensor([[0.3535, 0.4391, 0.5321, 0.1974],
        [0.8540, 0.1070, 0.4687, 0.5473],
        [0.4851, 0.2560, 0.0404, 0.9112],
        [0.1850, 0.6871, 0.4745, 0.4137],
        [0.4271, 0.6072, 0.7693, 0.6042]])


#### A 5 x 4 Tensor filled zeros and of dtype long

In [4]:
x = torch.zeros(5, 4, dtype=torch.long)
print(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


#### A 1 x 3 Tensor with Data Fed directly into it

In [5]:
x = torch.tensor([5, 3, 4])
print(x)

tensor([5, 3, 4])


#### A 2 x 3 Tensor with Data Directly Fed into it

In [6]:
x = torch.tensor([[6, 5, 4], [3, 2, 1]])
print(x)

tensor([[6, 5, 4],
        [3, 2, 1]])


#### A 5 x 4 Tensor with ones using new_one methods and passing the dimension and type as parameters

In [7]:
x = x.new_ones(5, 4, dtype=torch.double)      
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


#### A 1 x 4 Tensor with ones using new_one methods and passing the dimension and type as parameters

In [8]:
x = x.new_ones(1, 4, dtype=torch.double)      
print(x)

tensor([[1., 1., 1., 1.]], dtype=torch.float64)


#### A 5 x 4 Tensor with zeros using new_zero methods and passing the dimension and type as parameters

In [9]:
x = x.new_zeros(5, 4, dtype=torch.double)      
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


#### A 1 x 4 Tensor with zeros using new_zero methods and passing the dimension and type as parameters

In [10]:
x = x.new_zeros(1, 4, dtype=torch.double)      
print(x)

tensor([[0., 0., 0., 0.]], dtype=torch.float64)


#### Setting Dtype to Float

In [11]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.4822,  0.9900, -1.4706,  0.1237]])


#### Printing the Size of a Tensor

In [12]:
print(x.size())

torch.Size([1, 4])


# Operations with Tensors

#### Transpose

In [13]:
x.t()

tensor([[ 0.4822],
        [ 0.9900],
        [-1.4706],
        [ 0.1237]])

In [14]:
# Transpose (via permute)
x.permute(-1,0)

tensor([[ 0.4822],
        [ 0.9900],
        [-1.4706],
        [ 0.1237]])

#### Slicing

In [15]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [17]:
# Print the last column
print(x[:, -1])

tensor([3., 6., 9.])


In [18]:
# First 2 rows
print(x[:2, :])

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [19]:
# Lower right corner
print(x[-1:, -1:])

tensor([[9.]])


#### Addition

In [20]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
z = x + y
print(z)

tensor([[ 3,  4,  5],
        [ 7,  8,  9],
        [11, 12, 13]])


#### Subtraction

In [21]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
z = x - y
print(z)

tensor([[-1,  0,  1],
        [ 1,  2,  3],
        [ 3,  4,  5]])


#### Multiplication

In [22]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
z = x * y
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


#### Scalar Addition

In [23]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z = x + 1
print(z)

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])


#### Scalar Subtraction

In [24]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z = x - 1
print(z)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


#### Scalar Multiplication

In [25]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z = x * 2
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


#### Scalar Divion

In [26]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z = x / 2
print(z)

tensor([[0, 1, 1],
        [2, 2, 3],
        [3, 4, 4]])


#### Alternate Method for Addition

In [27]:
print(torch.add(x, y))

tensor([[ 3,  4,  5],
        [ 7,  8,  9],
        [11, 12, 13]])


#### Adding In place i.e the tensor itself is modified
#### Adding x to y
Note : Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [28]:
y.add_(x)
print(y)

tensor([[ 3,  4,  5],
        [ 7,  8,  9],
        [11, 12, 13]])


#### NumPy Array-like indexing

In [29]:
print(x[:, 1])

tensor([2, 5, 8])


#### Resizing 
If you want to resize/reshape tensor, you can use torch.view:

In [30]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### Accessing the Element-wise Value of a Tensor
If you have one element tensor, use .item() to get the value as a Python number. For multiple elements, use a loop.

In [31]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5511])
-0.5511044263839722


In [32]:
x = torch.rand(5)
print(x)
for item in x:
    print(item.item())

tensor([0.5220, 0.7616, 0.5711, 0.9260, 0.4563])
0.5220347046852112
0.7616415023803711
0.5711096525192261
0.9259992837905884
0.4563405513763428


#### Converting a Torch Tensor to a NumPy Array

In [33]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [34]:
b = a.numpy()
print(b)    

[ 1.  1.  1.  1.  1.]


In [35]:
# Notice how modifying the Tensor a will affect the Numpy Array b
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


#### Converting NumPy Array to Torch Tensor

In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[ 1.  1.  1.  1.  1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [37]:
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [38]:
a = np.random.rand(4,3)
a

array([[ 0.91246066,  0.80521745,  0.32433465],
       [ 0.40543706,  0.83589715,  0.38593214],
       [ 0.54402132,  0.75691535,  0.05474423],
       [ 0.86447768,  0.23961401,  0.03174321]])

In [39]:
b = torch.from_numpy(a)
b

tensor([[0.9125, 0.8052, 0.3243],
        [0.4054, 0.8359, 0.3859],
        [0.5440, 0.7569, 0.0547],
        [0.8645, 0.2396, 0.0317]], dtype=torch.float64)

In [40]:
b.numpy()

array([[ 0.91246066,  0.80521745,  0.32433465],
       [ 0.40543706,  0.83589715,  0.38593214],
       [ 0.54402132,  0.75691535,  0.05474423],
       [ 0.86447768,  0.23961401,  0.03174321]])

In [41]:
# Multiply PyTorch Tensor by 5, in place
b.mul_(5)

tensor([[4.5623, 4.0261, 1.6217],
        [2.0272, 4.1795, 1.9297],
        [2.7201, 3.7846, 0.2737],
        [4.3224, 1.1981, 0.1587]], dtype=torch.float64)

In [42]:
# Numpy array matches new values from Tensor
a

array([[ 4.56230329,  4.02608727,  1.62167323],
       [ 2.02718529,  4.17948574,  1.92966072],
       [ 2.72010661,  3.78457677,  0.27372113],
       [ 4.32238841,  1.19807006,  0.15871603]])