# PyTorch Tensor Notebook

### The Data Spartan

#### Helpful Resourses: 
1. https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
2. https://pytorch.org/docs/stable/tensors.html

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate 
computing.

In [1]:
from __future__ import print_function
import torch

# Tensor Initialization

#### An Uninitialized 5 X 4 Tensor 

In [2]:
x = torch.empty(5, 4)
print(x)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])


#### A Randomly Initialized 5 x 4 Tensor

In [3]:
x = torch.rand(5, 4)
print(x)

tensor([[0.9366, 0.7039, 0.9663, 0.9756],
        [0.4464, 0.2159, 0.2059, 0.8994],
        [0.8387, 0.6116, 0.1286, 0.0867],
        [0.2191, 0.0376, 0.2570, 0.0135],
        [0.2769, 0.7705, 0.0625, 0.1840]])


#### A 5 x 4 Tensor filled zeros and of dtype long

In [4]:
x = torch.zeros(5, 4, dtype=torch.long)
print(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


#### A 1 x 3 Tensor with Data Fed directly into it

In [5]:
x = torch.tensor([5, 3, 4])
print(x)

tensor([5, 3, 4])


#### A 2 x 3 Tensor with Data Directly Fed into it

In [6]:
x = torch.tensor([[6, 5, 4], [3, 2, 1]])
print(x)

tensor([[6, 5, 4],
        [3, 2, 1]])


#### A 5 x 4 Tensor with ones using new_one methods and passing the dimension and type as parameters

In [7]:
x = x.new_ones(5, 4, dtype=torch.double)      
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


#### A 1 x 4 Tensor with ones using new_one methods and passing the dimension and type as parameters

In [8]:
x = x.new_ones(1, 4, dtype=torch.double)      
print(x)

tensor([[1., 1., 1., 1.]], dtype=torch.float64)


#### A 5 x 4 Tensor with zeros using new_zero methods and passing the dimension and type as parameters

In [9]:
x = x.new_zeros(5, 4, dtype=torch.double)      
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


#### A 1 x 4 Tensor with zeros using new_zero methods and passing the dimension and type as parameters

In [10]:
x = x.new_zeros(1, 4, dtype=torch.double)      
print(x)

tensor([[0., 0., 0., 0.]], dtype=torch.float64)


#### Setting Dtype to Float

In [11]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.2301, -1.3129, -0.4919, -0.8395]])


#### Printing the Size of a Tensor

In [12]:
print(x.size())

torch.Size([1, 4])


# Operations with Tensors

#### Transpose

In [13]:
x.t()

tensor([[ 1.2301],
        [-1.3129],
        [-0.4919],
        [-0.8395]])

In [14]:
# Transpose (via permute)
x.permute(-1,0)

tensor([[ 1.2301],
        [-1.3129],
        [-0.4919],
        [-0.8395]])

#### Slicing

In [20]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [21]:
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [17]:
# Print the last column
print(x[:, -1])

tensor([3., 6., 9.])


In [18]:
# First 2 rows
print(x[:2, :])

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [19]:
# Lower right corner
print(x[-1:, -1:])

tensor([[9.]])


#### Addition

In [21]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
z = x + y
print(z)

tensor([[ 3,  4,  5],
        [ 7,  8,  9],
        [11, 12, 13]])


#### Subtraction

In [20]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
z = x - y
print(z)

tensor([[-1,  0,  1],
        [ 1,  2,  3],
        [ 3,  4,  5]])


#### Multiplication

In [19]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
z = x * y
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


#### Scalar Addition

In [22]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z = x + 1
print(z)

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])


#### Scalar Subtraction

In [23]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z = x - 1
print(z)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


#### Scalar Multiplication

In [24]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z = x * 2
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


#### Scalar Divion

In [25]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
z = x / 2
print(z)

tensor([[0, 1, 1],
        [2, 2, 3],
        [3, 4, 4]])


#### Alternate Method for Addition

In [26]:
print(torch.add(x, y))

tensor([[ 3,  4,  5],
        [ 7,  8,  9],
        [11, 12, 13]])


#### Adding In place i.e the tensor itself is modified
#### Adding x to y
Note : Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [28]:
y.add_(x)
print(y)

tensor([[ 3,  4,  5],
        [ 7,  8,  9],
        [11, 12, 13]])


#### NumPy Array-like indexing

In [29]:
print(x[:, 1])

tensor([2, 5, 8])


#### Resizing 
If you want to resize/reshape tensor, you can use torch.view:

In [30]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### Accessing the Element-wise Value of a Tensor
If you have one element tensor, use .item() to get the value as a Python number. For multiple elements, use a loop.

In [31]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9311])
-0.9310659170150757


In [32]:
x = torch.rand(5)
print(x)
for item in x:
    print(item.item())

tensor([0.3642, 0.6216, 0.4180, 0.5538, 0.1641])
0.36418384313583374
0.6215569376945496
0.4180213212966919
0.553777277469635
0.16414296627044678


#### Converting a Torch Tensor to a NumPy Array

In [33]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [34]:
b = a.numpy()
print(b)    

[ 1.  1.  1.  1.  1.]


In [35]:
# Notice how modifying the Tensor a will affect the Numpy Array b
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


#### Converting NumPy Array to Torch Tensor

In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[ 1.  1.  1.  1.  1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [37]:
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
